import {
  User,
  Contact,
  Shield,
  VenetianMask,
  GraduationCap,
  Crosshair,
  Bomb,
  Skull,
  Syringe,
  FlaskConical,
  Hammer,
  Wine,
  Dumbbell,
  Trophy,
  Scissors,
  Anchor,
  Fish,
  Building,
  Trees,
  Warehouse,
  DoorOpen,
  Hospital,
  Landmark,
  Store,
  Book,
  Ship,
  Briefcase,
  Hotel,
  TrainFront,
  Plane,
  Martini,
  Grid,
  Dices,
  Car,
  Key,
  Lightbulb,
  Bed,
  Utensils,
  Coffee,
  Music,
  Bath,
  Search,
  Sword,
  Sword as Knife,
  Flame,
  Droplets,
  PenTool,
  Zap,
  MapPin,
  Pyramid,
  Ghost,
  Sofa,
  Armchair,
  type LucideIcon
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  // People icons
  'user': User,
  'user-tie': Contact,
  'user-nurse': User,
  'user-shield': Shield,
  'user-secret': VenetianMask,
  'user-graduate': GraduationCap,

  // Weapon icons
  'knife': Knife,
  'sword': Sword,
  'bomb': Bomb,
  'skull': Skull,
  'syringe': Syringe,
  'flask': FlaskConical,
  'hammer': Hammer,
  'wine-bottle': Wine,
  'dumbbell': Dumbbell,
  'trophy': Trophy,
  'scissors': Scissors,
  'anchor': Anchor,
  'fish': Fish,
  'flame': Flame,
  'candlestick': Flame,
  'poison': Skull,
  'droplets': Droplets,
  'pen': PenTool,
  'zap': Zap,
  'crosshair': Crosshair,

  // Location icons
  'building': Building,
  'tree': Trees,
  'warehouse': Warehouse,
  'door-open': DoorOpen,
  'hospital': Hospital,
  'landmark': Landmark,
  'store': Store,
  'book': Book,
  'ship': Ship,
  'briefcase': Briefcase,
  'hotel': Hotel,
  'train': TrainFront,
  'plane': Plane,
  'glass-cheers': Martini,
  'chess': Grid,
  'dice': Dices,
  'car': Car,
  'key': Key,
  'lightbulb': Lightbulb,
  'bed': Bed,
  'utensils': Utensils,
  'coffee': Coffee,
  'couch': Sofa,
  'chair': Armchair,
  'map-pin': MapPin,
  'pyramid': Pyramid,
  'ghost': Ghost,
  'music': Music,
  'bath': Bath,
  'search': Search,
  'grid': Grid
};

export function getIcon(iconName: string): LucideIcon {
  return iconMap[iconName] || User; // Default to user icon if not found
}
